// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-zgl-T129KSLW8_s5T5xxDdOwbMomzLU',
    appId: '1:1013232893484:web:d2d1c29bec98fc9eb2db89',
    messagingSenderId: '1013232893484',
    projectId: 'flutterproject-c4bea',
    authDomain: 'flutterproject-c4bea.firebaseapp.com',
    storageBucket: 'flutterproject-c4bea.firebasestorage.app',
    measurementId: 'G-MNZN5YKM8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuLPiyyeM5aiNl6NwItwRhhAqlQPHXye0',
    appId: '1:1013232893484:android:09e68261cb07f059b2db89',
    messagingSenderId: '1013232893484',
    projectId: 'flutterproject-c4bea',
    storageBucket: 'flutterproject-c4bea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2jZfONj73ylFfc-bY4DDLB41wzul3sHM',
    appId: '1:1013232893484:ios:e4b461ee7ad381a1b2db89',
    messagingSenderId: '1013232893484',
    projectId: 'flutterproject-c4bea',
    storageBucket: 'flutterproject-c4bea.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2jZfONj73ylFfc-bY4DDLB41wzul3sHM',
    appId: '1:1013232893484:ios:e4b461ee7ad381a1b2db89',
    messagingSenderId: '1013232893484',
    projectId: 'flutterproject-c4bea',
    storageBucket: 'flutterproject-c4bea.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-zgl-T129KSLW8_s5T5xxDdOwbMomzLU',
    appId: '1:1013232893484:web:9f213cc33c6e10cab2db89',
    messagingSenderId: '1013232893484',
    projectId: 'flutterproject-c4bea',
    authDomain: 'flutterproject-c4bea.firebaseapp.com',
    storageBucket: 'flutterproject-c4bea.firebasestorage.app',
    measurementId: 'G-9N3WG9D7N4',
  );
}
